In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from matplotlib import rcParams
rcParams['font.sans-serif']=['SimHei']
rcParams['font.sans-serif']=['STHeiti']

In [15]:
df=pd.read_csv('C:/Users/Lenovo/Desktop/house_sales.csv')

In [17]:
print('总记录数：',len(df))
print('字段数量：',len(df.columns))
df.head(5)

总记录数： 106118
字段数量： 12

,city,address,area,floor,name,price,province,rooms,toward,unit,year,origin_url
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建,https://hf.esf.fang.com/chushou/3_404230646.htm
1,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建,https://hf.esf.fang.com/chushou/3_404230646.htm
2,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建,https://hf.esf.fang.com/chushou/3_404304901.htm
3,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建,https://hf.esf.fang.com/chushou/3_404304901.htm
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37㎡,中层（共22层）,文一名门金隅,32万,安徽,2室1厅,南北向,8649元/㎡,2017年建,https://hf.esf.fang.com/chushou/3_404372096.htm

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106118 entries, 0 to 106117
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   city        106118 non-null  object
 1   address     104452 non-null  object
 2   area        105324 non-null  object
 3   floor       104024 non-null  object
 4   name        105564 non-null  object
 5   price       105564 non-null  object
 6   province    106118 non-null  object
 7   rooms       104036 non-null  object
 8   toward      105240 non-null  object
 9   unit        105564 non-null  object
 10  year        57736 non-null   object
 11  origin_url  105564 non-null  object
dtypes: object(12)
memory usage: 9.7+ MB

In [19]:
df.drop(columns='origin_url',inplace=True)

In [20]:
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
1,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
3,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37㎡,中层（共22层）,文一名门金隅,32万,安徽,2室1厅,南北向,8649元/㎡,2017年建

In [21]:
df.isna().sum()

city            0
address      1666
area          794
floor        2094
name          554
price         554
province        0
rooms        2082
toward        878
unit          554
year        48382
dtype: int64

In [23]:
df.dropna(inplace=True)
print(len(df))

57520

In [24]:
df.duplicated().sum()

np.int64(29416)

In [26]:
df.drop_duplicates(inplace=True)
print(len(df))

28104

In [27]:
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37㎡,中层（共22层）,文一名门金隅,32万,安徽,2室1厅,南北向,8649元/㎡,2017年建
6,合肥,龙岗-长江东路与和县里交口,50㎡,高层（共30层）,柏庄金座,46万,安徽,2室1厅,南向,9200元/㎡,2019年建
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120㎡,中层（共27层）,天目未来,158万,安徽,4室2厅,南向,13167元/㎡,2012年建

In [50]:
# 1. 提取所有数字（支持整数/小数）
df['area'] = df['area'].astype(str).str.extract(r'(\d+\.?\d*)')

# 2. 转换成数值类型，异常值转为 NaN
df['area'] = pd.to_numeric(df['area'], errors='coerce')

# 3. 验证结果
print(df[['area']].head())
print("数据类型：", df['area'].dtype)

    area
0   90.0
2   95.0
4   37.0
6   50.0
8  120.0
数据类型： float64

In [51]:
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32万,安徽,2室1厅,南北向,8649元/㎡,2017年建
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46万,安徽,2室1厅,南向,9200元/㎡,2019年建
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158万,安徽,4室2厅,南向,13167元/㎡,2012年建

In [59]:
df['price']=df['price'].str.replace('万','')
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128,安徽,3室2厅,南北向,14222元/㎡,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132,安徽,3室2厅,南向,13895元/㎡,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32,安徽,2室1厅,南北向,8649元/㎡,2017年建
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46,安徽,2室1厅,南向,9200元/㎡,2019年建
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158,安徽,4室2厅,南向,13167元/㎡,2012年建

In [61]:
df['price']=df['price'].astype(float)

In [62]:
df['toward'].value_counts()

toward
南北向    15946
南向      9405
东南向     1114
东向       448
西南向      308
北向       276
西向       182
东西向      162
西北向      138
东北向      125
Name: count, dtype: int64

In [63]:
df['toward']=df['toward'].astype('category')

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28104 entries, 0 to 106088
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   city      28104 non-null  object
 1   address   28104 non-null  object
 2   area      28104 non-null  float64
 3   floor     28104 non-null  object
 4   name      28104 non-null  object
 5   price     28104 non-null  float64
 6   province  28104 non-null  object
 7   rooms     28104 non-null  object
 8   toward    28104 non-null  category
 9   unit      28104 non-null  object
 10  year      28104 non-null  object
dtypes: category(1), float64(2), object(8)
memory usage: 2.4+ MB

In [69]:
# 提取所有数字（支持整数/小数）
df['unit'] = df['unit'].astype(str).str.extract(r'(\d+\.?\d*)')

# 转为数值类型
df['unit'] = pd.to_numeric(df['unit'], errors='coerce')

In [70]:
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128.0,安徽,3室2厅,南北向,14222.0,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132.0,安徽,3室2厅,南向,13895.0,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32.0,安徽,2室1厅,南北向,8649.0,2017年建
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46.0,安徽,2室1厅,南向,9200.0,2019年建
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158.0,安徽,4室2厅,南向,13167.0,2012年建

In [73]:
# 提取所有数字（支持整数/小数）
df['year'] = df['year'].astype(str).str.extract(r'(\d+\.?\d*)')

# 转为数值类型
df['year'] = pd.to_numeric(df['year'], errors='coerce')
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128.0,安徽,3室2厅,南北向,14222.0,2013.0
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132.0,安徽,3室2厅,南向,13895.0,2019.0
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32.0,安徽,2室1厅,南北向,8649.0,2017.0
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46.0,安徽,2室1厅,南向,9200.0,2019.0
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158.0,安徽,4室2厅,南向,13167.0,2012.0

In [75]:
df=df[(df['area']<600)&(df['area']>20)]
df.head()
len(df)

28079

In [81]:
Q1=df['price'].quantile(0.25)
Q3=df['price'].quantile(0.75)
IQR=Q3-Q1
low_price=Q1-1.5*IQR
high_price=Q3+1.5*IQR
df=df[(df['price']<high_price)&(df['price']>low_price)]

In [84]:
df.loc[:, 'district'] = df['address'].str.split('-').str[0]
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year,district
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128.0,安徽,3室2厅,南北向,14222.0,2013.0,龙岗
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132.0,安徽,3室2厅,南向,13895.0,2019.0,生态公园
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32.0,安徽,2室1厅,南北向,8649.0,2017.0,撮镇
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46.0,安徽,2室1厅,南向,9200.0,2019.0,龙岗
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158.0,安徽,4室2厅,南向,13167.0,2012.0,新亚汽车站

In [89]:
df.sample(10) #看楼层格式是否都一致

,city,address,area,floor,name,price,province,rooms,toward,unit,year,district
38866,诸暨,世纪广场-袍江-世纪广场-卧龙金湖湾,144.00,低层（共15层）,卧龙金湖湾,150.00,浙江,3室2厅,南向,10417.0,2010.0,世纪广场
8662,聊城,东昌府-卫育北路(阿华制药南面200米处)、香江市场,100.00,低层（共6层）,一诺水城龙园,97.00,山东,3室2厅,南向,9700.0,2010.0,东昌府
18954,乐亭,凤凰新城-长宁道与友谊路交汇处东南角,114.80,中层（共25层）,水电首郡,205.00,河北,3室2厅,南北向,17857.0,2015.0,凤凰新城
2856,常宁,华新开发区-华新开发区太阳广场边,164.00,高层（共7层）,三化馨园,65.80,湖南,5室2厅,南北向,4012.0,2010.0,华新开发区
100108,咸宁,五洲新天地-咸宁,70.71,中层（共25层）,五洲新天地,39.00,湖北,2室2厅,南北向,5515.0,2016.0,五洲新天地
5524,邯郸,"丛台-人民路交警队南侧,创鑫阳光城三期(阳光嘉苑)",88.00,中层（共6层）,苹果怡园,100.00,河北,3室2厅,南北向,11364.0,2008.0,丛台
103070,中牟,北站-中州大道与北环交叉口西100米路南,134.00,中层（共32层）,山顶御鑫城,175.88,河南,3室2厅,南北向,13125.0,2012.0,北站
23584,金堂,中和镇-翡翠半岛国际社区老成仁路6号(红星路南延线与,82.00,中层（共18层）,翡翠半岛国际社区,150.00,四川,2室2厅,南向,18293.0,2013.0,中和镇
18898,乐亭,大润发-唐山市建华西道与翔云道交叉口,51.50,低层（共5层）,体育场楼,84.00,河北,2室1厅,南北向,16311.0,1988.0,大润发
76680,台山,台城街道-台城镇环市东,86.00,中层（共8层）,源华苑,46.00,广东,3室2厅,南向,5349.0,1998.0,台城街道

In [98]:
# 1. 先显式创建副本，消除 SettingWithCopyWarning
df = df.copy()
# 2. 用正则直接提取楼层类型（完全无视空格/格式）
df['floor_type'] = df['floor'].str.extract(r'^(.*?)\s*\(')
# 3. 验证结果
print(df[['floor', 'total_floor']].head())

      floor  total_floor
0  中层（共18层）         18.0
2  中层（共18层）         18.0
4  中层（共22层）         22.0
6  高层（共30层）         30.0
8  中层（共27层）         27.0

In [99]:
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year,district,floor_type,floor_clean,total_floor
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128.0,安徽,3室2厅,南北向,14222.0,2013.0,龙岗,NaN,中层（共18层）,18.0
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132.0,安徽,3室2厅,南向,13895.0,2019.0,生态公园,NaN,中层（共18层）,18.0
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32.0,安徽,2室1厅,南北向,8649.0,2017.0,撮镇,NaN,中层（共22层）,22.0
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46.0,安徽,2室1厅,南向,9200.0,2019.0,龙岗,NaN,高层（共30层）,30.0
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158.0,安徽,4室2厅,南向,13167.0,2012.0,新亚汽车站,NaN,中层（共27层）,27.0

In [100]:
# 1. 定义直辖市列表
municipalities = ['北京', '上海', '天津', '重庆']

# 2. 新增 is_municipality 列：1=直辖市，0=非直辖市
df['is_municipality'] = df['province'].isin(municipalities).astype(int)

# 3. 查看结果（可选）
print(df[['province', 'is_municipality']].value_counts())
print(df[['city', 'province', 'is_municipality']].head())

province  is_municipality
江苏        0                  2950
山东        0                  2616
河北        0                  2463
河南        0                  1996
广东        0                  1787
浙江        0                  1786
四川        0                  1361
安徽        0                  1313
湖南        0                  1159
福建        0                  1115
广西        0                  1068
湖北        0                  1042
陕西        0                   721
江西        0                   634
云南        0                   611
辽宁        0                   553
贵州        0                   531
海南        0                   514
吉林        0                   467
山西        0                   363
甘肃        0                   257
直辖市       0                   230
黑龙江       0                   197
内蒙古       0                   108
重庆        1                    92
宁夏        0                    73
天津        1                    72
新疆        0                    56
Name: count, dtype: int64
  city province  is_municipality
0   合肥       安徽                0
2   合肥       安徽                0
4   合肥       安徽                0
6   合肥       安徽                0
8   合肥       安徽                0

In [103]:
df.sample(5) #验证代码是否正确

,city,address,area,floor,name,price,province,rooms,toward,unit,year,district,floor_type,floor_clean,total_floor,is_municipality
9482,南通,城东版块-南通市小石桥东侧,48.0,中层（共6层）,新桥新村,69.8,江苏,2室1厅,南北向,14542.0,1996.0,城东版块,NaN,中层（共6层）,6.0,0
34968,新密,市财政局-嵩山路与航海路交汇处北500米路西,58.1,高层（共32层）,升龙城,100.0,河南,2室2厅,北向,17212.0,2014.0,市财政局,NaN,高层（共32层）,32.0,0
48234,蓟州,武清-下朱庄街京津快速路西侧,114.7,中层（共5层）,龙湾城,185.0,天津,3室2厅,南北向,16129.0,2014.0,武清,NaN,中层（共5层）,5.0,1
46582,湖州,西南新城-夹山路与二环西路交汇处(沿夹山路往东约300,90.0,中层（共11层）,泛港润合,70.0,浙江,3室2厅,南北向,7778.0,2018.0,西南新城,NaN,中层（共11层）,11.0,0
54504,三沙,老城-老城开发区北二环路与富音北路交汇处,61.0,高层（共23层）,景园悦海湾,82.0,海南,2室2厅,南向,13443.0,2018.0,老城,NaN,高层（共23层）,23.0,0

In [104]:
# 提取卧室数量（匹配“室”前面的数字）
df['bedrooms'] = df['rooms'].str.extract(r'(\d+)室').astype(float)

# 提取客厅数量（匹配“厅”前面的数字）
df['livingrooms'] = df['rooms'].str.extract(r'(\d+)厅').astype(float)

In [105]:
# 计算楼龄（处理空值）
df['building_age'] = 2026 - df['year']
df['building_age'] = pd.to_numeric(df['building_age'], errors='coerce')

In [106]:
# 定义价格区间（单位：万元）
price_bins = [0, 50, 100, 150, 200, float('inf')]
price_labels = ['0-50万', '50-100万', '100-150万', '150-200万', '200万以上']

# 生成价格分段标签
df['price_labels'] = pd.cut(
    df['price'], 
    bins=price_bins, 
    labels=price_labels, 
    right=False  # 左闭右开，避免边界值重复
)

In [107]:
# 验证结果
print(df[['rooms', 'bedrooms', 'livingrooms', 'year', 'building_age', 'price', 'price_labels']].head())

  rooms  bedrooms  livingrooms    year  building_age  price price_labels
0  3室2厅       3.0          2.0  2013.0          13.0  128.0     100-150万
2  3室2厅       3.0          2.0  2019.0           7.0  132.0     100-150万
4  2室1厅       2.0          1.0  2017.0           9.0   32.0        0-50万
6  2室1厅       2.0          1.0  2019.0           7.0   46.0        0-50万
8  4室2厅       4.0          2.0  2012.0          14.0  158.0     150-200万

In [108]:
df.sample(5)

,city,address,area,floor,name,price,province,rooms,toward,unit,year,district,floor_type,floor_clean,total_floor,is_municipality,bedrooms,livingrooms,building_age,price_labels
55698,威海,中心城区-威海荣成市崂山屯村,88.2,低层（共17层）,长青海世界,65.0,山东,3室2厅,南北向,7370.0,2019.0,中心城区,NaN,低层（共17层）,17.0,0,3.0,2.0,7.0,50-100万
69008,莱阳,大学城-观海路与学院路交汇处南(莱山一中西侧),125.0,低层（共29层）,万科翡翠大道,158.8,山东,3室2厅,南北向,12704.0,2019.0,大学城,NaN,低层（共29层）,29.0,0,3.0,2.0,7.0,150-200万
48308,蓟州,"杭州道-福州道与车站北路交口处,鸿正家园与奥林花园后",88.0,中层（共5层）,莱茵春天,127.0,天津,3室2厅,南北向,14432.0,2009.0,杭州道,NaN,中层（共5层）,5.0,1,3.0,2.0,17.0,100-150万
54688,三沙,金江-金江镇北侧1公里处金马大道边上(金江影剧院北,64.6,低层（共20层）,四季春城,61.0,海南,2室2厅,南北向,9443.0,2018.0,金江,NaN,低层（共20层）,20.0,0,2.0,2.0,8.0,50-100万
51124,宁德,体育场-天湖东路南侧福宁路西侧,119.0,中层（共28层）,盛辉仕林东湖,175.0,福建,3室2厅,南北向,14706.0,2012.0,体育场,NaN,中层（共28层）,28.0,0,3.0,2.0,14.0,150-200万